// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voltha_protos/health.proto

package org.opencord.voltha;

public final class Health {
  private Health() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HealthStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:voltha.HealthStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Current state of health of this Voltha instance
     * </pre>
     *
     * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
     */
    int getStateValue();
    /**
     * <pre>
     * Current state of health of this Voltha instance
     * </pre>
     *
     * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
     */
    org.opencord.voltha.Health.HealthStatus.HealthState getState();
  }
  /**
   * <pre>
   * Encode health status of a Voltha instance
   * </pre>
   *
   * Protobuf type {@code voltha.HealthStatus}
   */
  public  static final class HealthStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:voltha.HealthStatus)
      HealthStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthStatus.newBuilder() to construct.
    private HealthStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthStatus() {
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opencord.voltha.Health.internal_static_voltha_HealthStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opencord.voltha.Health.internal_static_voltha_HealthStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opencord.voltha.Health.HealthStatus.class, org.opencord.voltha.Health.HealthStatus.Builder.class);
    }

    /**
     * <pre>
     * Health states
     * </pre>
     *
     * Protobuf enum {@code voltha.HealthStatus.HealthState}
     */
    public enum HealthState
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * The instance is healthy
       * </pre>
       *
       * <code>HEALTHY = 0;</code>
       */
      HEALTHY(0),
      /**
       * <pre>
       * The instance is overloaded, decrease query rate
       * </pre>
       *
       * <code>OVERLOADED = 1;</code>
       */
      OVERLOADED(1),
      /**
       * <pre>
       * The instance is in a critical condition, do not use it
       * </pre>
       *
       * <code>DYING = 2;</code>
       */
      DYING(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * The instance is healthy
       * </pre>
       *
       * <code>HEALTHY = 0;</code>
       */
      public static final int HEALTHY_VALUE = 0;
      /**
       * <pre>
       * The instance is overloaded, decrease query rate
       * </pre>
       *
       * <code>OVERLOADED = 1;</code>
       */
      public static final int OVERLOADED_VALUE = 1;
      /**
       * <pre>
       * The instance is in a critical condition, do not use it
       * </pre>
       *
       * <code>DYING = 2;</code>
       */
      public static final int DYING_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static HealthState valueOf(int value) {
        return forNumber(value);
      }

      public static HealthState forNumber(int value) {
        switch (value) {
          case 0: return HEALTHY;
          case 1: return OVERLOADED;
          case 2: return DYING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<HealthState>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          HealthState> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<HealthState>() {
              public HealthState findValueByNumber(int number) {
                return HealthState.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.opencord.voltha.Health.HealthStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final HealthState[] VALUES = values();

      public static HealthState valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private HealthState(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:voltha.HealthStatus.HealthState)
    }

    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <pre>
     * Current state of health of this Voltha instance
     * </pre>
     *
     * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
     */
    public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * Current state of health of this Voltha instance
     * </pre>
     *
     * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
     */
    public org.opencord.voltha.Health.HealthStatus.HealthState getState() {
      @SuppressWarnings("deprecation")
      org.opencord.voltha.Health.HealthStatus.HealthState result = org.opencord.voltha.Health.HealthStatus.HealthState.valueOf(state_);
      return result == null ? org.opencord.voltha.Health.HealthStatus.HealthState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (state_ != org.opencord.voltha.Health.HealthStatus.HealthState.HEALTHY.getNumber()) {
        output.writeEnum(1, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (state_ != org.opencord.voltha.Health.HealthStatus.HealthState.HEALTHY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.opencord.voltha.Health.HealthStatus)) {
        return super.equals(obj);
      }
      org.opencord.voltha.Health.HealthStatus other = (org.opencord.voltha.Health.HealthStatus) obj;

      if (state_ != other.state_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opencord.voltha.Health.HealthStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.Health.HealthStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.opencord.voltha.Health.HealthStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.opencord.voltha.Health.HealthStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Encode health status of a Voltha instance
     * </pre>
     *
     * Protobuf type {@code voltha.HealthStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:voltha.HealthStatus)
        org.opencord.voltha.Health.HealthStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.opencord.voltha.Health.internal_static_voltha_HealthStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.opencord.voltha.Health.internal_static_voltha_HealthStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.opencord.voltha.Health.HealthStatus.class, org.opencord.voltha.Health.HealthStatus.Builder.class);
      }

      // Construct using org.opencord.voltha.Health.HealthStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.opencord.voltha.Health.internal_static_voltha_HealthStatus_descriptor;
      }

      @java.lang.Override
      public org.opencord.voltha.Health.HealthStatus getDefaultInstanceForType() {
        return org.opencord.voltha.Health.HealthStatus.getDefaultInstance();
      }

      @java.lang.Override
      public org.opencord.voltha.Health.HealthStatus build() {
        org.opencord.voltha.Health.HealthStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.opencord.voltha.Health.HealthStatus buildPartial() {
        org.opencord.voltha.Health.HealthStatus result = new org.opencord.voltha.Health.HealthStatus(this);
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.opencord.voltha.Health.HealthStatus) {
          return mergeFrom((org.opencord.voltha.Health.HealthStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.opencord.voltha.Health.HealthStatus other) {
        if (other == org.opencord.voltha.Health.HealthStatus.getDefaultInstance()) return this;
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.opencord.voltha.Health.HealthStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.opencord.voltha.Health.HealthStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       * Current state of health of this Voltha instance
       * </pre>
       *
       * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
       */
      public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       * Current state of health of this Voltha instance
       * </pre>
       *
       * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
       */
      public Builder setStateValue(int value) {
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Current state of health of this Voltha instance
       * </pre>
       *
       * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
       */
      public org.opencord.voltha.Health.HealthStatus.HealthState getState() {
        @SuppressWarnings("deprecation")
        org.opencord.voltha.Health.HealthStatus.HealthState result = org.opencord.voltha.Health.HealthStatus.HealthState.valueOf(state_);
        return result == null ? org.opencord.voltha.Health.HealthStatus.HealthState.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Current state of health of this Voltha instance
       * </pre>
       *
       * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
       */
      public Builder setState(org.opencord.voltha.Health.HealthStatus.HealthState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Current state of health of this Voltha instance
       * </pre>
       *
       * <code>.voltha.HealthStatus.HealthState state = 1 [(.voltha.access) = READ_ONLY];</code>
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:voltha.HealthStatus)
    }

    // @@protoc_insertion_point(class_scope:voltha.HealthStatus)
    private static final org.opencord.voltha.Health.HealthStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.opencord.voltha.Health.HealthStatus();
    }

    public static org.opencord.voltha.Health.HealthStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthStatus>
        PARSER = new com.google.protobuf.AbstractParser<HealthStatus>() {
      @java.lang.Override
      public HealthStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.opencord.voltha.Health.HealthStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_voltha_HealthStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_voltha_HealthStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032voltha_protos/health.proto\022\006voltha\032\034go" +
      "ogle/api/annotations.proto\032\033google/proto" +
      "buf/empty.proto\032\030voltha_protos/meta.prot" +
      "o\"}\n\014HealthStatus\0226\n\005state\030\001 \001(\0162 .volth" +
      "a.HealthStatus.HealthStateB\005\350\366\315\035\001\"5\n\013Hea" +
      "lthState\022\013\n\007HEALTHY\020\000\022\016\n\nOVERLOADED\020\001\022\t\n" +
      "\005DYING\020\0022a\n\rHealthService\022P\n\017GetHealthSt" +
      "atus\022\026.google.protobuf.Empty\032\024.voltha.He" +
      "althStatus\"\017\202\323\344\223\002\t\022\007/healthBE\n\023org.openc" +
      "ord.volthaZ.github.com/opencord/voltha-p" +
      "rotos/v4/go/volthab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          org.opencord.voltha.common.Meta.getDescriptor(),
        });
    internal_static_voltha_HealthStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_voltha_HealthStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_voltha_HealthStatus_descriptor,
        new java.lang.String[] { "State", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(org.opencord.voltha.common.Meta.access);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    org.opencord.voltha.common.Meta.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
