// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: slice_service.proto

package org.etri.onosslice.sliceservice;

public final class ONOSSliceService {
  private ONOSSliceService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddSliceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:onossliceservice.AddSliceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 technology_profile_id = 1;</code>
     * @return The technologyProfileId.
     */
    int getTechnologyProfileId();

    /**
     * <code>string slice_name = 2;</code>
     * @return The sliceName.
     */
    java.lang.String getSliceName();
    /**
     * <code>string slice_name = 2;</code>
     * @return The bytes for sliceName.
     */
    com.google.protobuf.ByteString
        getSliceNameBytes();

    /**
     * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
     * @return The enum numeric value on the wire for sliceType.
     */
    int getSliceTypeValue();
    /**
     * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
     * @return The sliceType.
     */
    org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType getSliceType();

    /**
     * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
     * @return The enum numeric value on the wire for dbaType.
     */
    int getDbaTypeValue();
    /**
     * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
     * @return The dbaType.
     */
    org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType getDbaType();
  }
  /**
   * Protobuf type {@code onossliceservice.AddSliceRequest}
   */
  public static final class AddSliceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:onossliceservice.AddSliceRequest)
      AddSliceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddSliceRequest.newBuilder() to construct.
    private AddSliceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddSliceRequest() {
      sliceName_ = "";
      sliceType_ = 0;
      dbaType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddSliceRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddSliceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              technologyProfileId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              sliceName_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              sliceType_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              dbaType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.class, org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code onossliceservice.AddSliceRequest.SliceType}
     */
    public enum SliceType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SLICE_TYPE_BUSINESS = 0;</code>
       */
      SLICE_TYPE_BUSINESS(0),
      /**
       * <code>SLICE_TYPE_RESIDENTIAL = 1;</code>
       */
      SLICE_TYPE_RESIDENTIAL(1),
      /**
       * <code>SLICE_TYPE_MOBILE = 2;</code>
       */
      SLICE_TYPE_MOBILE(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SLICE_TYPE_BUSINESS = 0;</code>
       */
      public static final int SLICE_TYPE_BUSINESS_VALUE = 0;
      /**
       * <code>SLICE_TYPE_RESIDENTIAL = 1;</code>
       */
      public static final int SLICE_TYPE_RESIDENTIAL_VALUE = 1;
      /**
       * <code>SLICE_TYPE_MOBILE = 2;</code>
       */
      public static final int SLICE_TYPE_MOBILE_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static SliceType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static SliceType forNumber(int value) {
        switch (value) {
          case 0: return SLICE_TYPE_BUSINESS;
          case 1: return SLICE_TYPE_RESIDENTIAL;
          case 2: return SLICE_TYPE_MOBILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<SliceType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          SliceType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<SliceType>() {
              public SliceType findValueByNumber(int number) {
                return SliceType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final SliceType[] VALUES = values();

      public static SliceType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private SliceType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:onossliceservice.AddSliceRequest.SliceType)
    }

    /**
     * Protobuf enum {@code onossliceservice.AddSliceRequest.DbaType}
     */
    public enum DbaType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DBA_TYPE_SR_DBA = 0;</code>
       */
      DBA_TYPE_SR_DBA(0),
      /**
       * <code>DBA_TYPE_LL_DBA = 1;</code>
       */
      DBA_TYPE_LL_DBA(1),
      /**
       * <code>DBA_TYPE_CO_DBA = 2;</code>
       */
      DBA_TYPE_CO_DBA(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DBA_TYPE_SR_DBA = 0;</code>
       */
      public static final int DBA_TYPE_SR_DBA_VALUE = 0;
      /**
       * <code>DBA_TYPE_LL_DBA = 1;</code>
       */
      public static final int DBA_TYPE_LL_DBA_VALUE = 1;
      /**
       * <code>DBA_TYPE_CO_DBA = 2;</code>
       */
      public static final int DBA_TYPE_CO_DBA_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DbaType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DbaType forNumber(int value) {
        switch (value) {
          case 0: return DBA_TYPE_SR_DBA;
          case 1: return DBA_TYPE_LL_DBA;
          case 2: return DBA_TYPE_CO_DBA;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DbaType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DbaType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DbaType>() {
              public DbaType findValueByNumber(int number) {
                return DbaType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDescriptor().getEnumTypes().get(1);
      }

      private static final DbaType[] VALUES = values();

      public static DbaType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DbaType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:onossliceservice.AddSliceRequest.DbaType)
    }

    public static final int TECHNOLOGY_PROFILE_ID_FIELD_NUMBER = 1;
    private int technologyProfileId_;
    /**
     * <code>int32 technology_profile_id = 1;</code>
     * @return The technologyProfileId.
     */
    @java.lang.Override
    public int getTechnologyProfileId() {
      return technologyProfileId_;
    }

    public static final int SLICE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object sliceName_;
    /**
     * <code>string slice_name = 2;</code>
     * @return The sliceName.
     */
    @java.lang.Override
    public java.lang.String getSliceName() {
      java.lang.Object ref = sliceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sliceName_ = s;
        return s;
      }
    }
    /**
     * <code>string slice_name = 2;</code>
     * @return The bytes for sliceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSliceNameBytes() {
      java.lang.Object ref = sliceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sliceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SLICE_TYPE_FIELD_NUMBER = 3;
    private int sliceType_;
    /**
     * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
     * @return The enum numeric value on the wire for sliceType.
     */
    @java.lang.Override public int getSliceTypeValue() {
      return sliceType_;
    }
    /**
     * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
     * @return The sliceType.
     */
    @java.lang.Override public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType getSliceType() {
      @SuppressWarnings("deprecation")
      org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType result = org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.valueOf(sliceType_);
      return result == null ? org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.UNRECOGNIZED : result;
    }

    public static final int DBA_TYPE_FIELD_NUMBER = 4;
    private int dbaType_;
    /**
     * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
     * @return The enum numeric value on the wire for dbaType.
     */
    @java.lang.Override public int getDbaTypeValue() {
      return dbaType_;
    }
    /**
     * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
     * @return The dbaType.
     */
    @java.lang.Override public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType getDbaType() {
      @SuppressWarnings("deprecation")
      org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType result = org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.valueOf(dbaType_);
      return result == null ? org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (technologyProfileId_ != 0) {
        output.writeInt32(1, technologyProfileId_);
      }
      if (!getSliceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sliceName_);
      }
      if (sliceType_ != org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.SLICE_TYPE_BUSINESS.getNumber()) {
        output.writeEnum(3, sliceType_);
      }
      if (dbaType_ != org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.DBA_TYPE_SR_DBA.getNumber()) {
        output.writeEnum(4, dbaType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (technologyProfileId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, technologyProfileId_);
      }
      if (!getSliceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sliceName_);
      }
      if (sliceType_ != org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.SLICE_TYPE_BUSINESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, sliceType_);
      }
      if (dbaType_ != org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.DBA_TYPE_SR_DBA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, dbaType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest)) {
        return super.equals(obj);
      }
      org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest other = (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest) obj;

      if (getTechnologyProfileId()
          != other.getTechnologyProfileId()) return false;
      if (!getSliceName()
          .equals(other.getSliceName())) return false;
      if (sliceType_ != other.sliceType_) return false;
      if (dbaType_ != other.dbaType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TECHNOLOGY_PROFILE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTechnologyProfileId();
      hash = (37 * hash) + SLICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getSliceName().hashCode();
      hash = (37 * hash) + SLICE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + sliceType_;
      hash = (37 * hash) + DBA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dbaType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code onossliceservice.AddSliceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:onossliceservice.AddSliceRequest)
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.class, org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.Builder.class);
      }

      // Construct using org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        technologyProfileId_ = 0;

        sliceName_ = "";

        sliceType_ = 0;

        dbaType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceRequest_descriptor;
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest getDefaultInstanceForType() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest build() {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest buildPartial() {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest result = new org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest(this);
        result.technologyProfileId_ = technologyProfileId_;
        result.sliceName_ = sliceName_;
        result.sliceType_ = sliceType_;
        result.dbaType_ = dbaType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest) {
          return mergeFrom((org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest other) {
        if (other == org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDefaultInstance()) return this;
        if (other.getTechnologyProfileId() != 0) {
          setTechnologyProfileId(other.getTechnologyProfileId());
        }
        if (!other.getSliceName().isEmpty()) {
          sliceName_ = other.sliceName_;
          onChanged();
        }
        if (other.sliceType_ != 0) {
          setSliceTypeValue(other.getSliceTypeValue());
        }
        if (other.dbaType_ != 0) {
          setDbaTypeValue(other.getDbaTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int technologyProfileId_ ;
      /**
       * <code>int32 technology_profile_id = 1;</code>
       * @return The technologyProfileId.
       */
      @java.lang.Override
      public int getTechnologyProfileId() {
        return technologyProfileId_;
      }
      /**
       * <code>int32 technology_profile_id = 1;</code>
       * @param value The technologyProfileId to set.
       * @return This builder for chaining.
       */
      public Builder setTechnologyProfileId(int value) {
        
        technologyProfileId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 technology_profile_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTechnologyProfileId() {
        
        technologyProfileId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sliceName_ = "";
      /**
       * <code>string slice_name = 2;</code>
       * @return The sliceName.
       */
      public java.lang.String getSliceName() {
        java.lang.Object ref = sliceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sliceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string slice_name = 2;</code>
       * @return The bytes for sliceName.
       */
      public com.google.protobuf.ByteString
          getSliceNameBytes() {
        java.lang.Object ref = sliceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sliceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string slice_name = 2;</code>
       * @param value The sliceName to set.
       * @return This builder for chaining.
       */
      public Builder setSliceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sliceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string slice_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSliceName() {
        
        sliceName_ = getDefaultInstance().getSliceName();
        onChanged();
        return this;
      }
      /**
       * <code>string slice_name = 2;</code>
       * @param value The bytes for sliceName to set.
       * @return This builder for chaining.
       */
      public Builder setSliceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sliceName_ = value;
        onChanged();
        return this;
      }

      private int sliceType_ = 0;
      /**
       * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
       * @return The enum numeric value on the wire for sliceType.
       */
      @java.lang.Override public int getSliceTypeValue() {
        return sliceType_;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
       * @param value The enum numeric value on the wire for sliceType to set.
       * @return This builder for chaining.
       */
      public Builder setSliceTypeValue(int value) {
        
        sliceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
       * @return The sliceType.
       */
      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType getSliceType() {
        @SuppressWarnings("deprecation")
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType result = org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.valueOf(sliceType_);
        return result == null ? org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType.UNRECOGNIZED : result;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
       * @param value The sliceType to set.
       * @return This builder for chaining.
       */
      public Builder setSliceType(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.SliceType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sliceType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.SliceType slice_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSliceType() {
        
        sliceType_ = 0;
        onChanged();
        return this;
      }

      private int dbaType_ = 0;
      /**
       * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
       * @return The enum numeric value on the wire for dbaType.
       */
      @java.lang.Override public int getDbaTypeValue() {
        return dbaType_;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
       * @param value The enum numeric value on the wire for dbaType to set.
       * @return This builder for chaining.
       */
      public Builder setDbaTypeValue(int value) {
        
        dbaType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
       * @return The dbaType.
       */
      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType getDbaType() {
        @SuppressWarnings("deprecation")
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType result = org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.valueOf(dbaType_);
        return result == null ? org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType.UNRECOGNIZED : result;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
       * @param value The dbaType to set.
       * @return This builder for chaining.
       */
      public Builder setDbaType(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.DbaType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dbaType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.onossliceservice.AddSliceRequest.DbaType dba_type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDbaType() {
        
        dbaType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:onossliceservice.AddSliceRequest)
    }

    // @@protoc_insertion_point(class_scope:onossliceservice.AddSliceRequest)
    private static final org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest();
    }

    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddSliceRequest>
        PARSER = new com.google.protobuf.AbstractParser<AddSliceRequest>() {
      @java.lang.Override
      public AddSliceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddSliceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddSliceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddSliceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddSliceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:onossliceservice.AddSliceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * Protobuf type {@code onossliceservice.AddSliceResponse}
   */
  public static final class AddSliceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:onossliceservice.AddSliceResponse)
      AddSliceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AddSliceResponse.newBuilder() to construct.
    private AddSliceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AddSliceResponse() {
      result_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AddSliceResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AddSliceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.class, org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object result_;
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse)) {
        return super.equals(obj);
      }
      org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse other = (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse) obj;

      if (!getResult()
          .equals(other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code onossliceservice.AddSliceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:onossliceservice.AddSliceResponse)
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.class, org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.Builder.class);
      }

      // Construct using org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.internal_static_onossliceservice_AddSliceResponse_descriptor;
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse getDefaultInstanceForType() {
        return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse build() {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse buildPartial() {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse result = new org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse) {
          return mergeFrom((org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse other) {
        if (other == org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 1;</code>
       * @return The result.
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @return The bytes for result.
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:onossliceservice.AddSliceResponse)
    }

    // @@protoc_insertion_point(class_scope:onossliceservice.AddSliceResponse)
    private static final org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse();
    }

    public static org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AddSliceResponse>
        PARSER = new com.google.protobuf.AbstractParser<AddSliceResponse>() {
      @java.lang.Override
      public AddSliceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AddSliceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AddSliceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AddSliceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code onossliceservice.SliceService}
   */
  public static abstract class SliceService
      implements com.google.protobuf.Service {
    protected SliceService() {}

    public interface Interface {
      /**
       * <code>rpc AddSlice(.onossliceservice.AddSliceRequest) returns (.onossliceservice.AddSliceResponse);</code>
       */
      public abstract void addSlice(
          com.google.protobuf.RpcController controller,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request,
          com.google.protobuf.RpcCallback<org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new SliceService() {
        @java.lang.Override
        public  void addSlice(
            com.google.protobuf.RpcController controller,
            org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request,
            com.google.protobuf.RpcCallback<org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse> done) {
          impl.addSlice(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.addSlice(controller, (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc AddSlice(.onossliceservice.AddSliceRequest) returns (.onossliceservice.AddSliceResponse);</code>
     */
    public abstract void addSlice(
        com.google.protobuf.RpcController controller,
        org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request,
        com.google.protobuf.RpcCallback<org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.etri.onosslice.sliceservice.ONOSSliceService.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.addSlice(controller, (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest)request,
            com.google.protobuf.RpcUtil.<org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends org.etri.onosslice.sliceservice.ONOSSliceService.SliceService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void addSlice(
          com.google.protobuf.RpcController controller,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request,
          com.google.protobuf.RpcCallback<org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.class,
            org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse addSlice(
          com.google.protobuf.RpcController controller,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse addSlice(
          com.google.protobuf.RpcController controller,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.etri.onosslice.sliceservice.ONOSSliceService.AddSliceResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:onossliceservice.SliceService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onossliceservice_AddSliceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onossliceservice_AddSliceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onossliceservice_AddSliceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onossliceservice_AddSliceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023slice_service.proto\022\020onossliceservice\"" +
      "\345\002\n\017AddSliceRequest\022\035\n\025technology_profil" +
      "e_id\030\001 \001(\005\022\022\n\nslice_name\030\002 \001(\t\022?\n\nslice_" +
      "type\030\003 \001(\0162+.onossliceservice.AddSliceRe" +
      "quest.SliceType\022;\n\010dba_type\030\004 \001(\0162).onos" +
      "sliceservice.AddSliceRequest.DbaType\"W\n\t" +
      "SliceType\022\027\n\023SLICE_TYPE_BUSINESS\020\000\022\032\n\026SL" +
      "ICE_TYPE_RESIDENTIAL\020\001\022\025\n\021SLICE_TYPE_MOB" +
      "ILE\020\002\"H\n\007DbaType\022\023\n\017DBA_TYPE_SR_DBA\020\000\022\023\n" +
      "\017DBA_TYPE_LL_DBA\020\001\022\023\n\017DBA_TYPE_CO_DBA\020\002\"" +
      "\"\n\020AddSliceResponse\022\016\n\006result\030\001 \001(\t2c\n\014S" +
      "liceService\022S\n\010AddSlice\022!.onossliceservi" +
      "ce.AddSliceRequest\032\".onossliceservice.Ad" +
      "dSliceResponse\"\000Bp\n\037org.etri.onosslice.s" +
      "liceserviceB\020ONOSSliceServiceZ8github.co" +
      "m/opencord/voltha-protos/v4/go/onosslice" +
      "service\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_onossliceservice_AddSliceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_onossliceservice_AddSliceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onossliceservice_AddSliceRequest_descriptor,
        new java.lang.String[] { "TechnologyProfileId", "SliceName", "SliceType", "DbaType", });
    internal_static_onossliceservice_AddSliceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_onossliceservice_AddSliceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onossliceservice_AddSliceResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
